version: "3.9"  # Specify the Docker Compose file version
services:
  app:
    build: .  # Build the Flask app image from the current directory
    ports:
      - "5000:80"  # Map port 5000 of the container to port 80 on the host
    depends_on:
      - db  # Ensure the app starts after the database
  db:
    image: postgres:latest  # Use the latest Postgres image
    user: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234  # Set your desired password
      POSTGRES_DB: DEFAULT_MAKERSBNB_PROJECT  # Set your desired database name
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data
      - ./sql:/docker-entrypoint-initdb.d # Mount the seed files for the database
volumes:
  postgres-data:  # Define a volume for database data